production:
  adapter: postgresql
  encoding: unicode
  database: codeless_production
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: codeless_development
  pool: 5
  host: localhost
