# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebdc354dea83dbbab82546ab81a8db16a02c250ad3db6cd84b76be2faa7beb0a90b736e531ba191d1665c87d94fabb6d89fa31fcf80ca8b49d68851cf48e658b

test:
  secret_key_base: 5f0708ad06f3f3b0f0b4722568d423714786269cb00d6a4aa7e2aa860413ec97c26f0c874198486c784bd3d149422989820fd9e6f352d549ae7a04e641c3b065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
